openapi: 3.0.3
info:
  title: Admin Company API
  version: 1.0.0
  description: API endpoints to manage companies (create, update, delete, list, get details) with multilingual fields and image upload.

servers:
  - url: http://localhost:5000/api/admin/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        JWT access token should be sent as a cookie named `accessToken`.
        The frontend must send credentials with requests (e.g., `credentials: 'include'` in fetch).

  schemas:
    MultilingualString:
      type: object
      properties:
        en:
          type: string
          example: "English text"
        ar:
          type: string
          example: "النص العربي"
      required:
        - en
        - ar

    Location:
      type: array
      description: Coordinates [longitude, latitude]
      items:
        type: number
      minItems: 2
      maxItems: 2
      example: [35.6895, 139.6917]

    Company:
      type: object
      properties:
        _id:
          type: string
          example: "64dca33fbc4c57f8b12e1234"
        name:
          $ref: '#/components/schemas/MultilingualString'
        address:
          $ref: '#/components/schemas/MultilingualString'
        image:
          type: string
          description: Base64 encoded image string
          example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..."
        shortdescription:
          $ref: '#/components/schemas/MultilingualString'
        longdescription:
          $ref: '#/components/schemas/MultilingualString'
        location:
          $ref: '#/components/schemas/Location'
        request:
          type: string
          enum: ["free", "reverc", "agree"]
          example: "free"
        branches:
          type: array
          items:
            type: string
            description: Branch ObjectId
        numberOfEmployees:
          type: integer
          example: 25
        notes:
          $ref: '#/components/schemas/MultilingualString'
        machinery:
          $ref: '#/components/schemas/MultilingualString'
        createdAt:
          type: string
          format: date-time
          example: "2023-08-20T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-08-21T15:30:00Z"
      required:
        - name
        - address
        - location

    CompanyCreateRequest:
      type: object
      description: Data to create a company. Send image as multipart form data (field name "image").
      properties:
        name:
          $ref: '#/components/schemas/MultilingualString'
        address:
          $ref: '#/components/schemas/MultilingualString'
        shortDescription:
          $ref: '#/components/schemas/MultilingualString'
          description: Optional short description
        longDescription:
          $ref: '#/components/schemas/MultilingualString'
          description: Optional long description
        location:
          $ref: '#/components/schemas/Location'
          description: Coordinates [longitude, latitude]
        machinery:
          $ref: '#/components/schemas/MultilingualString'
          description: Optional machinery description
        notes:
          $ref: '#/components/schemas/MultilingualString'
          description: Optional notes
        numberOfEmployees:
          type: integer
          description: Number of employees
        request:
          type: string
          enum: ["free", "reverc", "agree"]
          default: "free"
        newdata:
          type: array
          description: Optional additional multilingual fields, e.g. [{ "fieldKey": { "en": "val", "ar": "val" }}]
          items:
            type: object
      required:
        - name
        - address
        - location

    CompanyUpdateRequest:
      type: object
      description: Fields to update a company. Send image as multipart form data (field name "image").
      properties:
        name:
          $ref: '#/components/schemas/MultilingualString'
        address:
          $ref: '#/components/schemas/MultilingualString'
        shortDescription:
          $ref: '#/components/schemas/MultilingualString'
        longDescription:
          $ref: '#/components/schemas/MultilingualString'
        location:
          $ref: '#/components/schemas/Location'
        machinery:
          $ref: '#/components/schemas/MultilingualString'
        notes:
          $ref: '#/components/schemas/MultilingualString'
        numberOfEmployees:
          type: integer
        request:
          type: string
          enum: ["free", "reverc", "agree"]
        newdata:
          type: array
          items:
            type: object

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Error message here"
        error:
          type: string
          example: "Detailed error message"

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operation successful"

paths:

  /companies:
    post:
      summary: Create a new company
      tags: [Companies]
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: '#/components/schemas/CompanyCreateRequest'
                - type: object
                  properties:
                    image:
                      type: string
                      format: binary
                      description: Image file upload
        required: true
      responses:
        '201':
          description: Company created successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      companyId:
                        type: string
                        example: "64dca33fbc4c57f8b12e1234"
        '400':
          description: Missing or invalid fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Get all companies (public)
      tags: [Companies]
      responses:
        '200':
          description: List of all companies
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  companies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Company'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /companies/{companyId}:
    get:
      summary: Get single company by ID (public)
      tags: [Companies]
      parameters:
        - name: companyId
          in: path
          required: true
          description: Company ObjectId
          schema:
            type: string
      responses:
        '200':
          description: Company details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  company:
                    $ref: '#/components/schemas/Company'
        '404':
          description: Company not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update company (admin protected)
      tags: [Companies]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          description: Company ObjectId
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: '#/components/schemas/CompanyUpdateRequest'
                - type: object
                  properties:
                    image:
                      type: string
                      format: binary
                      description: Image file upload
        required: true
      responses:
        '200':
          description: Company updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Company updated successfully"
                  company:
                    $ref: '#/components/schemas/Company'
        '404':
          description: Company not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete company (admin protected)
      tags: [Companies]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          description: Company ObjectId
          schema:
            type: string
      responses:
        '200':
          description: Company and related branches/centers deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          description: Company not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

tags:
  - name: Companies
    description: Operations related to company entities

